apiVersion: apps/v1
kind: Deployment
metadata:
  name: myexpress-app-deployment
  labels:
    app:  myexpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myexpress-app
  template:
    metadata:
      labels:
        app:  myexpress-app
    spec:
      containers:
      - name: myexpress-app
        image: minhmt/myexpress-app
        ports:           
          - containerPort: 3000                     
---
apiVersion: v1 
kind: Service
metadata: 
  name: myexpress-app-service
spec:
  type: NodePort
  selector:
    app: myexpress-app
  ports:
    - protocol: TCP
      port: 3000  
      targetPort: 3000
      


